In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [9]:
df=pd.read_csv('data_cleaned.csv')
df.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1     ...      Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1     ...            1        0        0        0   
1         0        0        1     ...            1        0        0        0   
2         0        1        0     ...            1        0        0        0   
3         0        0        1     ...            1        0        0        0   
4         1        1        0     ...            1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [10]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [14]:
from sklearn.model_selection import train_test_split as tt
train_x,val_x,train_y,val_y=tt(x,y,random_state=101,stratify=y)

In [34]:
from sklearn.linear_model import LogisticRegression as LR
lr=LR(random_state=101)
lr.fit(train_x,train_y)
s1=lr.score(train_x,train_y)
predict1=lr.predict(val_x)
s1_1=lr.score(val_x,val_y)
predict1,lr.score(val_x,val_y),s1

(array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 0], dtype=int64), 0.7757847533632287, 0.8278443113772455)

In [35]:
from sklearn.neighbors import KNeighborsClassifier as KNN
knn=KNN(n_neighbors=9)
knn.fit(train_x,train_y)
s2=knn.score(train_x,train_y)
predict2=knn.predict(val_x)
s2_2=knn.score(val_x,val_y)
predict2,knn.score(val_x,val_y),s2

(array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0], dtype=int64), 0.7219730941704036, 0.7664670658682635)

In [36]:
from sklearn.tree import DecisionTreeClassifier as DT
dd=DT(max_depth=7)
dd.fit(train_x,train_y)
s3=dd.score(train_x,train_y)
predict3=dd.predict(val_x)
s3_3=dd.score(val_x,val_y)
predict3,dd.score(val_x,val_y),s3

(array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0], dtype=int64), 0.7713004484304933, 0.8892215568862275)

In [52]:
p=[]
from statistics import mode
array=np.array([])
for i in range(len(val_x)):
    array=np.append(array,mode([predict1[i],predict2[i],predict3[i]]))


In [56]:
from sklearn.metrics import accuracy_score 
accuracy_score(val_y,array)

0.7847533632286996

In [57]:
accuracy_score(predict1,val_y),accuracy_score(predict2,val_y),accuracy_score(predict3,val_y)

(0.7757847533632287, 0.7219730941704036, 0.7713004484304933)

## Average

In [60]:
df1=pd.read_csv('train_cleaned.csv')
df1.head()

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0         9.30         0.016047  249.8092                       1999   
1         5.92         0.019278   48.2692                       2009   
2        17.50         0.016760  141.6180                       1999   
3        19.20         0.000000  182.0950                       1998   
4         8.93         0.000000   53.8614                       1987   

   Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0          3735.1380                    0                         1   
1           443.4228                    0                         0   
2          2097.2700                    0                         1   
3           732.3800                    0                         0   
4           994.7052                    0                         1   

   Item_Fat_Content_Regular  Item_Fat_Content_low fat  Item_Fat_Content_reg  \
0                         0                         0                     0   
1                         1                         0                     0   
2                         0                         0                     0   
3                         1                         0                     0   
4                         0                         0                     0   

               ...                Outlet_Size_High  Outlet_Size_Medium  \
0              ...                               0                   1   
1              ...                               0                   1   
2              ...                               0                   1   
3              ...                               0                   0   
4              ...                               1                   0   

   Outlet_Size_Small  Outlet_Location_Type_Tier 1  \
0                  0                            1   
1                  0                            0   
2                  0                            1   
3                  0                            0   
4                  0                            0   

   Outlet_Location_Type_Tier 2  Outlet_Location_Type_Tier 3  \
0                            0                            0   
1                            0                            1   
2                            0                            0   
3                            0                            1   
4                            0                            1   

   Outlet_Type_Grocery Store  Outlet_Type_Supermarket Type1  \
0                          0                              1   
1                          0                              0   
2                          0                              1   
3                          1                              0   
4                          0                              1   

   Outlet_Type_Supermarket Type2  Outlet_Type_Supermarket Type3  
0                              0                              0  
1                              1                              0  
2                              0                              0  
3                              0                              0  
4                              0                              0  

[5 rows x 46 columns]

In [63]:
x1=df1.drop(['Item_Outlet_Sales'],axis=1)
y1=df1['Item_Outlet_Sales']

In [65]:
train1_x,val1_x,train1_y,val1_y=tt(x1,y1,random_state=101,shuffle=False)

In [77]:
from sklearn.linear_model import LinearRegression as LR
from sklearn.neighbors import KNeighborsRegressor as KN
from sklearn.tree import DecisionTreeRegressor as DT

In [78]:
lr=LR()
lr.fit(train1_x,train1_y)
s11=lr.score(train1_x,train1_y)
predict1_1=lr.predict(val1_x)
predict1_1,lr.score(val1_x,val1_y),s11

(array([2443.32513354, 2788.36657095, 2169.73477778, ..., 1530.66091668,
        1398.84548916, 1216.55011886]), 0.5551582433748833, 0.5658331947629717)

In [79]:
kn=KN(n_neighbors=9)
kn.fit(train1_x,train1_y)
s22=lr.score(train1_x,train1_y)
predict2_2=lr.predict(val1_x)
predict2_2,lr.score(val1_x,val1_y),s22

(array([2443.32513354, 2788.36657095, 2169.73477778, ..., 1530.66091668,
        1398.84548916, 1216.55011886]), 0.5551582433748833, 0.5658331947629717)

In [83]:
dt=DT(max_depth=7)
dt.fit(train1_x,train1_y)
s33=dt.score(train1_x,train1_y)
predict3_3=dt.predict(val1_x)
predict3_3,dt.score(val1_x,val1_y),s33

(array([2413.81776312, 2822.71913115,  585.22631071, ..., 1320.45894667,
        1595.93215694, 1317.66301346]), 0.5735374916724253, 0.6298008118653939)

In [91]:
array1=np.array([])
for i in range(len(val1_x)):
    array1=np.append(array1,mean([predict1_1[i],predict2_2[i],predict3_3[i]]))

In [94]:
from sklearn.metrics import r2_score
r2_score(val1_y,array1)

0.5770618359508068

In [96]:
r2_score(val1_y,predict1_1),r2_score(val1_y,predict2_2),r2_score(val1_y,predict3_3)


(0.5551582433748833, 0.5551582433748833, 0.5735374916724253)

### weighted

In [98]:
array2=np.array([])
for i in range(len(val1_x)):
    array2=np.append(array2,mean([predict1_1[i],predict1_1[i],predict2_2[i],predict3_3[i],predict3_3[i]]))


In [100]:
r2_score(val1_y,array2)

0.5795492932887825

In [102]:
r2_score(val1_y,predict1_1),r2_score(val1_y,predict2_2),r2_score(val1_y,predict3_3)

(0.5551582433748833, 0.5551582433748833, 0.5735374916724253)

#### rank

In [105]:
q=pd.DataFrame({'score':[r2_score(val1_y,predict1_1),r2_score(val1_y,predict2_2),r2_score(val1_y,predict3_3)]})
q

score
0  0.555158
1  0.555158
2  0.573537

In [112]:
q['rank']=q['score'].rank().astype('int')
q['rank']
q['weight']=q['rank']/q['rank'].sum()
q

score  rank  weight
0  0.555158     1     0.2
1  0.555158     1     0.2
2  0.573537     3     0.6