In [208]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('train_bm.csv')
df

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [4]:
features=df.drop(['Item_Outlet_Sales'],axis=1)
y=df['Item_Outlet_Sales']


In [8]:
import featuretools as ft

In [10]:
es=ft.EntitySet(id='bigmart')
es

Entityset: bigmart
  Entities:
  Relationships:
    No relationships

In [12]:
es.entity_from_dataframe(entity_id='data1',dataframe=features,make_index=True,index='index')

RuntimeError: Cannot make index: index variable already present

In [16]:
a,b=ft.dfs(entityset=es,target_entity='data1',max_depth=1,trans_primitives=['add_numeric', 'multiply_numeric'])

ValueError: ('Unknown transform primitive add_numeric. ', 'Call ft.primitives.list_primitives() to get', ' a list of available primitives')

In [18]:
df=pd.read_csv('data_cleaned.csv')
df

Survived        Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0           0  22.000000   7.2500         0         0         1           0   
1           1  38.000000  71.2833         1         0         0           1   
2           1  26.000000   7.9250         0         0         1           1   
3           1  35.000000  53.1000         1         0         0           1   
4           0  35.000000   8.0500         0         0         1           0   
..        ...        ...      ...       ...       ...       ...         ...   
886         0  27.000000  13.0000         0         1         0           0   
887         1  19.000000  30.0000         1         0         0           1   
888         0  29.699118  23.4500         0         0         1           1   
889         1  26.000000  30.0000         1         0         0           0   
890         0  32.000000   7.7500         0         0         1           0   

     Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0           1        0        1  ...        1        0        0        0   
1           0        0        1  ...        1        0        0        0   
2           0        1        0  ...        1        0        0        0   
3           0        0        1  ...        1        0        0        0   
4           1        1        0  ...        1        0        0        0   
..        ...      ...      ...  ...      ...      ...      ...      ...   
886         1        1        0  ...        1        0        0        0   
887         0        1        0  ...        1        0        0        0   
888         0        0        1  ...        0        0        1        0   
889         1        1        0  ...        1        0        0        0   
890         1        1        0  ...        1        0        0        0   

     Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0          0        0        0           0           0           1  
1          0        0        0           1           0           0  
2          0        0        0           0           0           1  
3          0        0        0           0           0           1  
4          0        0        0           0           0           1  
..       ...      ...      ...         ...         ...         ...  
886        0        0        0           0           0           1  
887        0        0        0           0           0           1  
888        0        0        0           0           0           1  
889        0        0        0           1           0           0  
890        0        0        0           0           1           0  

[891 rows x 25 columns]

In [57]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

from sklearn.preprocessing import MinMaxScaler 
scaled=MinMaxScaler()
scaled_x=scaled.fit_transform(x)
x=pd.DataFrame(scaled_x,columns=x.columns)
from sklearn.model_selection import train_test_split as tt
train_x,val_x,train_y,val_y=tt(x,y,random_state=101,stratify=y)

In [58]:
from sklearn.linear_model import LogisticRegression 
lr=LogisticRegression()
lr.fit(train_x,train_y)
lr.score(train_x,train_y)

0.8248502994011976

In [144]:
predict1=lr.predict(val_x)
lr.score(val_x,val_y),predict1

(0.757847533632287,
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 0], dtype=int64))

In [127]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(train_x,train_y)
knn.score(train_x,train_y)

0.8592814371257484

In [145]:
predict2=lr.predict(val_x)
knn.score(val_x,val_y),predict2


(0.7892376681614349,
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 0], dtype=int64))

In [129]:
from sklearn.tree import DecisionTreeClassifier 
dd=DecisionTreeClassifier(max_depth=10)
dd.fit(train_x,train_y)
dd.score(train_x,train_y)

0.9461077844311377

In [146]:
predict3=lr.predict(val_x)
dd.score(val_x,val_y),predict3

(0.7713004484304933,
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 0], dtype=int64))

In [134]:
from statistics import mode
final1=np.array([])
for i in range(len(val_x)):
    final1=np.append(final1,mode([predict1[i],predict2[i],predict3[i]]))
final1

array([0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
       1., 0.])

In [132]:
from sklearn.metrics import accuracy_score as af

In [137]:
af(val_y,final1)

0.757847533632287

In [142]:
af(val_y,predict1)

0.757847533632287

In [147]:
af(predict2,val_y)

0.757847533632287

In [149]:
df=pd.read_csv('train_cleaned.csv')
df

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0           9.300         0.016047  249.8092                       1999   
1           5.920         0.019278   48.2692                       2009   
2          17.500         0.016760  141.6180                       1999   
3          19.200         0.000000  182.0950                       1998   
4           8.930         0.000000   53.8614                       1987   
...           ...              ...       ...                        ...   
8518        6.865         0.056783  214.5218                       1987   
8519        8.380         0.046982  108.1570                       2002   
8520       10.600         0.035186   85.1224                       2004   
8521        7.210         0.145221  103.1332                       2009   
8522       14.800         0.044878   75.4670                       1997   

      Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0             3735.1380                    0                         1   
1              443.4228                    0                         0   
2             2097.2700                    0                         1   
3              732.3800                    0                         0   
4              994.7052                    0                         1   
...                 ...                  ...                       ...   
8518          2778.3834                    0                         1   
8519           549.2850                    0                         0   
8520          1193.1136                    0                         1   
8521          1845.5976                    0                         0   
8522           765.6700                    0                         1   

      Item_Fat_Content_Regular  Item_Fat_Content_low fat  \
0                            0                         0   
1                            1                         0   
2                            0                         0   
3                            1                         0   
4                            0                         0   
...                        ...                       ...   
8518                         0                         0   
8519                         1                         0   
8520                         0                         0   
8521                         1                         0   
8522                         0                         0   

      Item_Fat_Content_reg  ...  Outlet_Size_High  Outlet_Size_Medium  \
0                        0  ...                 0                   1   
1                        0  ...                 0                   1   
2                        0  ...                 0                   1   
3                        0  ...                 0                   0   
4                        0  ...                 1                   0   
...                    ...  ...               ...                 ...   
8518                     0  ...                 1                   0   
8519                     0  ...                 0                   0   
8520                     0  ...                 0                   0   
8521                     0  ...                 0                   1   
8522                     0  ...                 0                   0   

      Outlet_Size_Small  Outlet_Location_Type_Tier 1  \
0                     0                            1   
1                     0                            0   
2                     0                            1   
3                     0                            0   
4                     0                            0   
...                 ...                          ...   
8518                  0                            0   
8519                  0                            0   
8520                  1                            0   
8521                  0                            0   
85

In [161]:
x=df.drop(['Item_Outlet_Sales'],axis=1)
y=df['Item_Outlet_Sales']

In [165]:
from sklearn.model_selection import train_test_split as tt
train_x,val_x,train_y,val_y=tt(x,y,random_state=101,shuffle=False)

In [166]:
from sklearn.linear_model import LinearRegression 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [284]:
ll=LinearRegression()
ll.fit(train_x,train_y)
ll.score(train_x,train_y)
prediction1=ll.predict(val_x)
prediction1
a=ll.score(val_x,val_y)
a

0.5551582433748833

In [285]:
knn=KNeighborsRegressor(n_neighbors=9)
knn.fit(train_x,train_y)
knn.score(train_x,train_y)
prediction2=knn.predict(val_x)
prediction2
b=knn.score(val_x,val_y)
b

0.5007936087911619

In [286]:
dd=DecisionTreeRegressor(max_depth=7)
dd.fit(train_x,train_y)
dd.score(train_x,train_y)
prediction3=dd.predict(val_x)
prediction3
c=dd.score(val_x,val_y)
c

0.5735111622038214

In [222]:
from statistics import mean
final2=np.array([])
for i in range(len(val_x)):
    final2=np.append(final2,mean([prediction1[i],prediction2[i],prediction3[i]]))
    



In [224]:
from sklearn.metrics import r2_score as rr
rr(val_y,final2)

0.5761151765779289

In [226]:
from statistics import mean
final2=np.array([])
for i in range(len(val_x)):
    final2=np.append(final2,mean([prediction1[i],prediction1[i],prediction2[i],prediction3[i],prediction3[i]]))

In [228]:
rr(val_y,final2)

0.5810400870277518

In [242]:
df_t=pd.DataFrame({'score':[a,b,c]})
df_t['rank']=df_t['score'].rank().astype(int)
df_t['weight']=df_t['rank']/df_t['rank'].sum()
df_t

score  rank    weight
0  0.555158     2  0.333333
1  0.500794     1  0.166667
2  0.573539     3  0.500000

In [287]:
from sklearn.metrics import r2_score 
weight0=prediction1*float(df_t.loc[[0],['weight']].values)
weight1=prediction2*float(df_t.loc[[1],['weight']].values)
weight2=prediction3*float(df_t.loc[[2],['weight']].values)
total=weight0+weight1+weight2
r2_score(val_y,total)

0.5828316440450751

In [270]:
weight1

array([ 931.00614537, 1261.54481744, 1312.5223127 , ...,  535.85646186,
        920.29938946,  612.73022834])

In [273]:
weight2

array([1384.41766378, 1618.93838249,  335.64987972, ...,  757.33417741,
        915.32869714,  755.73060179])

In [275]:
total

array([3671.85589828, 4428.46788734, 2852.71834024, ..., 2142.94966498,
       2612.20869112, 2043.8386571 ])

In [278]:
e=pd.DataFrame({'predicted':total,'actual':val_y})
e

predicted     actual
6392  3671.855898  4277.7650
6393  4428.467887  1070.6064
6394  2852.718340  1001.3632
6395  3811.873591  2871.5954
6396  5220.212176  4287.7520
...           ...        ...
8518  5472.883738  2778.3834
8519  2696.623603   549.2850
8520  2142.949665  1193.1136
8521  2612.208691  1845.5976
8522  2043.838657   765.6700

[2131 rows x 2 columns]