# numpy practice


In [79]:
import numpy as np
l=[1,2,3],[5,6,7]
l=np.array(l)
print(l)
print(l.shape)
print(l.ndim)


[[1 2 3]
 [5 6 7]]
(2, 3)
2


In [80]:
import numpy as np
a=np.random.randint(1,100,16)
print(a)
a=a.reshape(2,2,2,2)
print(a)
print(a.ndim)



[50 52 55 78 70 14 26 14 93 87 31 31 90 13 66 32]
[[[[50 52]
   [55 78]]

  [[70 14]
   [26 14]]]


 [[[93 87]
   [31 31]]

  [[90 13]
   [66 32]]]]
4


In [81]:
import numpy as np
a=np.arange(1,11)
print(a.reshape(5,-91))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [82]:
import numpy as np
a=np.random.seed(10)
a=np.random.randint(1,100,20)
a.size


20

# Array slicing

# import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(3,2)
print(a)

# concept



In [83]:
a[1][1]

IndexError: invalid index to scalar variable.

In [ ]:
b=a[0:,1]
b.reshape(1,-9)

In [ ]:
a


In [ ]:
a[0:,0:]

In [ ]:
a[1:,1:]

In [ ]:
b=np.array([[1,2,3],[4,5,6,]])
print(b[0:,1].reshape(2,1))

In [85]:
import numpy as np
a=np.arange(1,11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
b=a[0:5].copy()
b[:]=0
print(b)
print(a)

[0 0 0 0 0]
[ 1  2  3  4  5  6  7  8  9 10]


In [94]:
import numpy as np
b=np.arange(1,11)
print(b)
c=[b>5]

print(b[c])

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]


D:\Anaconda setup\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [103]:
b[b%2==0]=0
print(b)
b[b>5]
print(b)

[1 0 3 0 5 0 7 0 9 0]
[1 0 3 0 5 0 7 0 9 0]


In [107]:
a
a//2

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [121]:
a
np.exp(a)
np.tan(a)


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [125]:
np.sum(a)

55

In [133]:
a=a.reshape(5,2)
np.min(a,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [146]:
a=a.reshape(10)
a


array([ 3,  4,  1,  2,  9, 10,  5,  6,  7,  8])

In [153]:
np.random.shuffle(a)
a
np.unique(a)
np.unique(a,return_index=True,return_counts=True)


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([2, 1, 9, 4, 3, 5, 0, 7, 6, 8], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [165]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]]).reshape(2,3)
b=np.array([[11,22,33],[44,55,66]]).reshape(2,3)
np.hstack((a,b))


array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [170]:
a=a.reshape(6)
a[a%2==0]=-1
a

array([ 1, -1,  3, -1,  5, -1])

In [174]:

%timeit [i for i in range(0,10)]


1.45 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit a=np.arange(0,10)
