# practice mode of numpy library

In [4]:
import numpy as np
a=np.random.seed(123)
a=np.random.randint(1,11,20)
a


array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2])

In [23]:

b=np.arange(0,32).reshape(16,2)
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]]
(16, 2)
2
int32


In [36]:
c=np.array([[1,2,3],[4,5,6]]).reshape(3,2)
print(c)
c[0,1]
c[0][1]
d=c[:2,:2].copy()
d[:]=0
print(d)
c


[[1 2]
 [3 4]
 [5 6]]
[[0 0]
 [0 0]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
a=np.arange(1,11)


a=a*2
a//2


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [72]:
a=np.arange(0,4).reshape(2,2)
print(a)
b=np.arange(0,4).reshape(2,2)
print(b)
c=np.arange(0,4).reshape(2,2)
print(c)
a+b-c

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


array([[0, 1],
       [2, 3]])

In [76]:
np.argmax(a)

3

In [90]:
a=np.array([1,2,3,4])%2
a=np.cos(a)
a

array([0.54030231, 1.        , 0.54030231, 1.        ])

In [93]:
a=np.arange(1,11).reshape(2,5)
print(a)
a.sum()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


55

In [99]:
n=np.cumsum(a,axis=1)
n

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]], dtype=int32)

In [113]:

g=np.random.shuffle(e)
print(g)
np.unique(e)
np.unique(e,return_index=True,return_counts=False)




None


(array([ 1,  2,  3,  4,  5,  8,  9, 10]),
 array([7, 0, 5, 4, 3, 1, 8, 2], dtype=int64))

In [117]:
a=np.arange(0,4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [127]:
x=[]
x=[i for i in range(1,100)]
print(x)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [128]:
import numpy as np
%timeit a=np.arange(1,100)
a

2.69 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([[0, 1],
       [2, 3]])

In [131]:
v_name='ankit'
_name=21
print(v_name+_name)

TypeError: can only concatenate str (not "int") to str

In [137]:
def zbc():
    print('my name is ankit')
zbc()

my name is ankit
